var jwt = require("jsonwebtoken");
var uuid4 = require("uuid4");
//var axios = require("axios");

const app_access_key = "63b2acc4b94ae6b37911f504";
const app_secret =
  "0HAc1fnLzjShQEeHPGslxflOfsorSl03Njhdgmc2YUWZ25SNxiqJCG9eXm12afQzXDk_0mgIJb3EfwM8qcHbxvv2B_3Y6_wScMHoWNvMGa6huwKMvShj_zxxFc_4g3IiY71Zfjr57GEHQwNBesOisdAWQV6wpWOWBoJ6U6XshZ4=";

function generateHmsManagementToken() {
  var payload = {
    access_key: app_access_key,
    type: "management",
    version: 2,
    iat: Math.floor(Date.now() / 1000),
    nbf: Math.floor(Date.now() / 1000),
  };

  return jwt.sign(payload, app_secret, {
    algorithm: "HS256",
    expiresIn: "24h",
    jwtid: uuid4(),
  });
}

function generateHmsUserToken(room_id, user_id, role) {
  var payload = {
    access_key: app_access_key,
    room_id: room_id,
    user_id: user_id,
    role: role,
    type: "app",
    version: 2,
    iat: Math.floor(Date.now() / 1000),
    nbf: Math.floor(Date.now() / 1000),
  };

  console.log('generating user token for ', payload)

  return jwt.sign(payload, app_secret, {
    algorithm: "HS256",
    expiresIn: "24h",
    jwtid: uuid4(),
  });
}

exports.handler = async function (event, context) {
  //const template_id = "6409ec935ec8ce8ab3c02b78" // assembly
  //const template_id = "63b2b613447a48e7edc2269d" // classic 
  
  try {
    const { room_name, user_id, role } = JSON.parse(event.body);

    console.log("Request to join from", user_id, role)

    // let res = await axios.post(
    //   "https://api.100ms.live/v2/rooms",
    //   {
    //     name: room_name,
    //     description: "generated by getHmsRoomToken.js",
    //     template_id: template_id,
    //     region: "eu",
    //   },
    //   {
    //     headers: {
    //       authorization:
    //         `Bearer ${generateHmsManagementToken()}`,
    //     },
    //   }
    // );

    // console.log(res.data)

    const MIT_WERKSTATT3_BETA = '6418f0914f410525264f0696'
    let room_id = MIT_WERKSTATT3_BETA

    return {
      statusCode: 200,
      body: JSON.stringify({
        token: generateHmsUserToken(room_id, user_id, role),
        // token: generateHmsUserToken(res.data.id, user_id, role),
        success: true,
        msg: "",
      }),
      headers: {
        "access-control-allow-origin": "*",
      },
    };
  } catch (e) {
    return {
      statusCode: 500,
      body: JSON.stringify(e),
      headers: {
        "access-control-allow-origin": "*",
      },
    };
  }
};
